#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Test")]
	public partial class ConnectDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAddrAnother(AddrAnother instance);
    partial void UpdateAddrAnother(AddrAnother instance);
    partial void DeleteAddrAnother(AddrAnother instance);
    partial void InsertAttorney(Attorney instance);
    partial void UpdateAttorney(Attorney instance);
    partial void DeleteAttorney(Attorney instance);
    partial void InsertTypeAccount(TypeAccount instance);
    partial void UpdateTypeAccount(TypeAccount instance);
    partial void DeleteTypeAccount(TypeAccount instance);
    partial void InsertLimitAccount(LimitAccount instance);
    partial void UpdateLimitAccount(LimitAccount instance);
    partial void DeleteLimitAccount(LimitAccount instance);
    partial void InsertCareerInformation(CareerInformation instance);
    partial void UpdateCareerInformation(CareerInformation instance);
    partial void DeleteCareerInformation(CareerInformation instance);
    partial void InsertAddrWork(AddrWork instance);
    partial void UpdateAddrWork(AddrWork instance);
    partial void DeleteAddrWork(AddrWork instance);
    partial void InsertRefPerSonInformation(RefPerSonInformation instance);
    partial void UpdateRefPerSonInformation(RefPerSonInformation instance);
    partial void DeleteRefPerSonInformation(RefPerSonInformation instance);
    partial void InsertInforCorporate(InforCorporate instance);
    partial void UpdateInforCorporate(InforCorporate instance);
    partial void DeleteInforCorporate(InforCorporate instance);
    partial void InsertTypeCareer(TypeCareer instance);
    partial void UpdateTypeCareer(TypeCareer instance);
    partial void DeleteTypeCareer(TypeCareer instance);
    partial void InsertAddrCurrent(AddrCurrent instance);
    partial void UpdateAddrCurrent(AddrCurrent instance);
    partial void DeleteAddrCurrent(AddrCurrent instance);
    partial void InsertInforPayment(InforPayment instance);
    partial void UpdateInforPayment(InforPayment instance);
    partial void DeleteInforPayment(InforPayment instance);
    partial void InsertGenerateLink(GenerateLink instance);
    partial void UpdateGenerateLink(GenerateLink instance);
    partial void DeleteGenerateLink(GenerateLink instance);
    partial void InsertAccount(Account instance);
    partial void UpdateAccount(Account instance);
    partial void DeleteAccount(Account instance);
    partial void InsertCustInformation(CustInformation instance);
    partial void UpdateCustInformation(CustInformation instance);
    partial void DeleteCustInformation(CustInformation instance);
    #endregion
		
		public ConnectDataDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TestConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ConnectDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConnectDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConnectDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConnectDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AddrAnother> AddrAnothers
		{
			get
			{
				return this.GetTable<AddrAnother>();
			}
		}
		
		public System.Data.Linq.Table<Attorney> Attorneys
		{
			get
			{
				return this.GetTable<Attorney>();
			}
		}
		
		public System.Data.Linq.Table<TypeAccount> TypeAccounts
		{
			get
			{
				return this.GetTable<TypeAccount>();
			}
		}
		
		public System.Data.Linq.Table<LimitAccount> LimitAccounts
		{
			get
			{
				return this.GetTable<LimitAccount>();
			}
		}
		
		public System.Data.Linq.Table<CareerInformation> CareerInformations
		{
			get
			{
				return this.GetTable<CareerInformation>();
			}
		}
		
		public System.Data.Linq.Table<AddrWork> AddrWorks
		{
			get
			{
				return this.GetTable<AddrWork>();
			}
		}
		
		public System.Data.Linq.Table<RefPerSonInformation> RefPerSonInformations
		{
			get
			{
				return this.GetTable<RefPerSonInformation>();
			}
		}
		
		public System.Data.Linq.Table<InforCorporate> InforCorporates
		{
			get
			{
				return this.GetTable<InforCorporate>();
			}
		}
		
		public System.Data.Linq.Table<TypeCareer> TypeCareers
		{
			get
			{
				return this.GetTable<TypeCareer>();
			}
		}
		
		public System.Data.Linq.Table<AddrCurrent> AddrCurrents
		{
			get
			{
				return this.GetTable<AddrCurrent>();
			}
		}
		
		public System.Data.Linq.Table<InforPayment> InforPayments
		{
			get
			{
				return this.GetTable<InforPayment>();
			}
		}
		
		public System.Data.Linq.Table<GenerateLink> GenerateLinks
		{
			get
			{
				return this.GetTable<GenerateLink>();
			}
		}
		
		public System.Data.Linq.Table<Account> Accounts
		{
			get
			{
				return this.GetTable<Account>();
			}
		}
		
		public System.Data.Linq.Table<CustInformation> CustInformations
		{
			get
			{
				return this.GetTable<CustInformation>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteNoSuccessSP")]
		public int DeleteNoSuccessSP([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pCustAcc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pCustAcc);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AddrAnother")]
	public partial class AddrAnother : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CustNo;
		
		private string _No;
		
		private string _Street;
		
		private string _Building;
		
		private string _Alley;
		
		private string _Locality;
		
		private string _District;
		
		private string _Province;
		
		private string _ZipCode;
		
		private string _Tel;
		
		private string _fax;
		
		private string _TelPhone;
		
		private string _Email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustNoChanging(string value);
    partial void OnCustNoChanged();
    partial void OnNoChanging(string value);
    partial void OnNoChanged();
    partial void OnStreetChanging(string value);
    partial void OnStreetChanged();
    partial void OnBuildingChanging(string value);
    partial void OnBuildingChanged();
    partial void OnAlleyChanging(string value);
    partial void OnAlleyChanged();
    partial void OnLocalityChanging(string value);
    partial void OnLocalityChanged();
    partial void OnDistrictChanging(string value);
    partial void OnDistrictChanged();
    partial void OnProvinceChanging(string value);
    partial void OnProvinceChanged();
    partial void OnZipCodeChanging(string value);
    partial void OnZipCodeChanged();
    partial void OnTelChanging(string value);
    partial void OnTelChanged();
    partial void OnfaxChanging(string value);
    partial void OnfaxChanged();
    partial void OnTelPhoneChanging(string value);
    partial void OnTelPhoneChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public AddrAnother()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CustNo
		{
			get
			{
				return this._CustNo;
			}
			set
			{
				if ((this._CustNo != value))
				{
					this.OnCustNoChanging(value);
					this.SendPropertyChanging();
					this._CustNo = value;
					this.SendPropertyChanged("CustNo");
					this.OnCustNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No", DbType="NVarChar(50)")]
		public string No
		{
			get
			{
				return this._No;
			}
			set
			{
				if ((this._No != value))
				{
					this.OnNoChanging(value);
					this.SendPropertyChanging();
					this._No = value;
					this.SendPropertyChanged("No");
					this.OnNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Street", DbType="NVarChar(50)")]
		public string Street
		{
			get
			{
				return this._Street;
			}
			set
			{
				if ((this._Street != value))
				{
					this.OnStreetChanging(value);
					this.SendPropertyChanging();
					this._Street = value;
					this.SendPropertyChanged("Street");
					this.OnStreetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Building", DbType="NVarChar(50)")]
		public string Building
		{
			get
			{
				return this._Building;
			}
			set
			{
				if ((this._Building != value))
				{
					this.OnBuildingChanging(value);
					this.SendPropertyChanging();
					this._Building = value;
					this.SendPropertyChanged("Building");
					this.OnBuildingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alley", DbType="NVarChar(50)")]
		public string Alley
		{
			get
			{
				return this._Alley;
			}
			set
			{
				if ((this._Alley != value))
				{
					this.OnAlleyChanging(value);
					this.SendPropertyChanging();
					this._Alley = value;
					this.SendPropertyChanged("Alley");
					this.OnAlleyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Locality", DbType="NVarChar(50)")]
		public string Locality
		{
			get
			{
				return this._Locality;
			}
			set
			{
				if ((this._Locality != value))
				{
					this.OnLocalityChanging(value);
					this.SendPropertyChanging();
					this._Locality = value;
					this.SendPropertyChanged("Locality");
					this.OnLocalityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_District", DbType="NVarChar(50)")]
		public string District
		{
			get
			{
				return this._District;
			}
			set
			{
				if ((this._District != value))
				{
					this.OnDistrictChanging(value);
					this.SendPropertyChanging();
					this._District = value;
					this.SendPropertyChanged("District");
					this.OnDistrictChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Province", DbType="NVarChar(50)")]
		public string Province
		{
			get
			{
				return this._Province;
			}
			set
			{
				if ((this._Province != value))
				{
					this.OnProvinceChanging(value);
					this.SendPropertyChanging();
					this._Province = value;
					this.SendPropertyChanged("Province");
					this.OnProvinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZipCode", DbType="NVarChar(50)")]
		public string ZipCode
		{
			get
			{
				return this._ZipCode;
			}
			set
			{
				if ((this._ZipCode != value))
				{
					this.OnZipCodeChanging(value);
					this.SendPropertyChanging();
					this._ZipCode = value;
					this.SendPropertyChanged("ZipCode");
					this.OnZipCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="NVarChar(50)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this.OnTelChanging(value);
					this.SendPropertyChanging();
					this._Tel = value;
					this.SendPropertyChanged("Tel");
					this.OnTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax", DbType="NVarChar(50)")]
		public string fax
		{
			get
			{
				return this._fax;
			}
			set
			{
				if ((this._fax != value))
				{
					this.OnfaxChanging(value);
					this.SendPropertyChanging();
					this._fax = value;
					this.SendPropertyChanged("fax");
					this.OnfaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelPhone", DbType="NVarChar(50)")]
		public string TelPhone
		{
			get
			{
				return this._TelPhone;
			}
			set
			{
				if ((this._TelPhone != value))
				{
					this.OnTelPhoneChanging(value);
					this.SendPropertyChanging();
					this._TelPhone = value;
					this.SendPropertyChanged("TelPhone");
					this.OnTelPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Attorney")]
	public partial class Attorney : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CustNo;
		
		private string _Name;
		
		private string _IDCard;
		
		private string _IDGovernment;
		
		private string _Another;
		
		private string _Nationality;
		
		private string _Expired;
		
		private string _CreateDate;
		
		private string _relationship;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustNoChanging(string value);
    partial void OnCustNoChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnIDCardChanging(string value);
    partial void OnIDCardChanged();
    partial void OnIDGovernmentChanging(string value);
    partial void OnIDGovernmentChanged();
    partial void OnAnotherChanging(string value);
    partial void OnAnotherChanged();
    partial void OnNationalityChanging(string value);
    partial void OnNationalityChanged();
    partial void OnExpiredChanging(string value);
    partial void OnExpiredChanged();
    partial void OnCreateDateChanging(string value);
    partial void OnCreateDateChanged();
    partial void OnrelationshipChanging(string value);
    partial void OnrelationshipChanged();
    #endregion
		
		public Attorney()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CustNo
		{
			get
			{
				return this._CustNo;
			}
			set
			{
				if ((this._CustNo != value))
				{
					this.OnCustNoChanging(value);
					this.SendPropertyChanging();
					this._CustNo = value;
					this.SendPropertyChanged("CustNo");
					this.OnCustNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCard", DbType="NVarChar(50)")]
		public string IDCard
		{
			get
			{
				return this._IDCard;
			}
			set
			{
				if ((this._IDCard != value))
				{
					this.OnIDCardChanging(value);
					this.SendPropertyChanging();
					this._IDCard = value;
					this.SendPropertyChanged("IDCard");
					this.OnIDCardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDGovernment", DbType="NVarChar(50)")]
		public string IDGovernment
		{
			get
			{
				return this._IDGovernment;
			}
			set
			{
				if ((this._IDGovernment != value))
				{
					this.OnIDGovernmentChanging(value);
					this.SendPropertyChanging();
					this._IDGovernment = value;
					this.SendPropertyChanged("IDGovernment");
					this.OnIDGovernmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Another", DbType="NVarChar(50)")]
		public string Another
		{
			get
			{
				return this._Another;
			}
			set
			{
				if ((this._Another != value))
				{
					this.OnAnotherChanging(value);
					this.SendPropertyChanging();
					this._Another = value;
					this.SendPropertyChanged("Another");
					this.OnAnotherChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nationality", DbType="NVarChar(50)")]
		public string Nationality
		{
			get
			{
				return this._Nationality;
			}
			set
			{
				if ((this._Nationality != value))
				{
					this.OnNationalityChanging(value);
					this.SendPropertyChanging();
					this._Nationality = value;
					this.SendPropertyChanged("Nationality");
					this.OnNationalityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expired", DbType="NVarChar(50)")]
		public string Expired
		{
			get
			{
				return this._Expired;
			}
			set
			{
				if ((this._Expired != value))
				{
					this.OnExpiredChanging(value);
					this.SendPropertyChanging();
					this._Expired = value;
					this.SendPropertyChanged("Expired");
					this.OnExpiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="NVarChar(50)")]
		public string CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_relationship", DbType="NVarChar(50)")]
		public string relationship
		{
			get
			{
				return this._relationship;
			}
			set
			{
				if ((this._relationship != value))
				{
					this.OnrelationshipChanging(value);
					this.SendPropertyChanging();
					this._relationship = value;
					this.SendPropertyChanged("relationship");
					this.OnrelationshipChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TypeAccount")]
	public partial class TypeAccount : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TypeID;
		
		private string _TypeName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTypeIDChanging(int value);
    partial void OnTypeIDChanged();
    partial void OnTypeNameChanging(string value);
    partial void OnTypeNameChanged();
    #endregion
		
		public TypeAccount()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TypeID
		{
			get
			{
				return this._TypeID;
			}
			set
			{
				if ((this._TypeID != value))
				{
					this.OnTypeIDChanging(value);
					this.SendPropertyChanging();
					this._TypeID = value;
					this.SendPropertyChanged("TypeID");
					this.OnTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeName", DbType="NVarChar(50)")]
		public string TypeName
		{
			get
			{
				return this._TypeName;
			}
			set
			{
				if ((this._TypeName != value))
				{
					this.OnTypeNameChanging(value);
					this.SendPropertyChanging();
					this._TypeName = value;
					this.SendPropertyChanged("TypeName");
					this.OnTypeNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LimitAccount")]
	public partial class LimitAccount : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CustNo;
		
		private int _TypeID;
		
		private System.Nullable<decimal> _Limt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustNoChanging(string value);
    partial void OnCustNoChanged();
    partial void OnTypeIDChanging(int value);
    partial void OnTypeIDChanged();
    partial void OnLimtChanging(System.Nullable<decimal> value);
    partial void OnLimtChanged();
    #endregion
		
		public LimitAccount()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CustNo
		{
			get
			{
				return this._CustNo;
			}
			set
			{
				if ((this._CustNo != value))
				{
					this.OnCustNoChanging(value);
					this.SendPropertyChanging();
					this._CustNo = value;
					this.SendPropertyChanged("CustNo");
					this.OnCustNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TypeID
		{
			get
			{
				return this._TypeID;
			}
			set
			{
				if ((this._TypeID != value))
				{
					this.OnTypeIDChanging(value);
					this.SendPropertyChanging();
					this._TypeID = value;
					this.SendPropertyChanged("TypeID");
					this.OnTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Limt", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Limt
		{
			get
			{
				return this._Limt;
			}
			set
			{
				if ((this._Limt != value))
				{
					this.OnLimtChanging(value);
					this.SendPropertyChanging();
					this._Limt = value;
					this.SendPropertyChanged("Limt");
					this.OnLimtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CareerInformation")]
	public partial class CareerInformation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CustNo;
		
		private System.Nullable<int> _ID;
		
		private string _Business;
		
		private string _Position;
		
		private string _Salary;
		
		private string _Experience;
		
		private string _OtherIncome;
		
		private string _OtherSourcesIncome;
		
		private string _AnnualSales;
		
		private System.Nullable<bool> _Political;
		
		private string _PoliticalPosition;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustNoChanging(string value);
    partial void OnCustNoChanged();
    partial void OnIDChanging(System.Nullable<int> value);
    partial void OnIDChanged();
    partial void OnBusinessChanging(string value);
    partial void OnBusinessChanged();
    partial void OnPositionChanging(string value);
    partial void OnPositionChanged();
    partial void OnSalaryChanging(string value);
    partial void OnSalaryChanged();
    partial void OnExperienceChanging(string value);
    partial void OnExperienceChanged();
    partial void OnOtherIncomeChanging(string value);
    partial void OnOtherIncomeChanged();
    partial void OnOtherSourcesIncomeChanging(string value);
    partial void OnOtherSourcesIncomeChanged();
    partial void OnAnnualSalesChanging(string value);
    partial void OnAnnualSalesChanged();
    partial void OnPoliticalChanging(System.Nullable<bool> value);
    partial void OnPoliticalChanged();
    partial void OnPoliticalPositionChanging(string value);
    partial void OnPoliticalPositionChanged();
    #endregion
		
		public CareerInformation()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CustNo
		{
			get
			{
				return this._CustNo;
			}
			set
			{
				if ((this._CustNo != value))
				{
					this.OnCustNoChanging(value);
					this.SendPropertyChanging();
					this._CustNo = value;
					this.SendPropertyChanged("CustNo");
					this.OnCustNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Business", DbType="NVarChar(50)")]
		public string Business
		{
			get
			{
				return this._Business;
			}
			set
			{
				if ((this._Business != value))
				{
					this.OnBusinessChanging(value);
					this.SendPropertyChanging();
					this._Business = value;
					this.SendPropertyChanged("Business");
					this.OnBusinessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="NVarChar(50)")]
		public string Position
		{
			get
			{
				return this._Position;
			}
			set
			{
				if ((this._Position != value))
				{
					this.OnPositionChanging(value);
					this.SendPropertyChanging();
					this._Position = value;
					this.SendPropertyChanged("Position");
					this.OnPositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Salary", DbType="NVarChar(50)")]
		public string Salary
		{
			get
			{
				return this._Salary;
			}
			set
			{
				if ((this._Salary != value))
				{
					this.OnSalaryChanging(value);
					this.SendPropertyChanging();
					this._Salary = value;
					this.SendPropertyChanged("Salary");
					this.OnSalaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Experience", DbType="NVarChar(50)")]
		public string Experience
		{
			get
			{
				return this._Experience;
			}
			set
			{
				if ((this._Experience != value))
				{
					this.OnExperienceChanging(value);
					this.SendPropertyChanging();
					this._Experience = value;
					this.SendPropertyChanged("Experience");
					this.OnExperienceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherIncome", DbType="NVarChar(50)")]
		public string OtherIncome
		{
			get
			{
				return this._OtherIncome;
			}
			set
			{
				if ((this._OtherIncome != value))
				{
					this.OnOtherIncomeChanging(value);
					this.SendPropertyChanging();
					this._OtherIncome = value;
					this.SendPropertyChanged("OtherIncome");
					this.OnOtherIncomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherSourcesIncome", DbType="NVarChar(50)")]
		public string OtherSourcesIncome
		{
			get
			{
				return this._OtherSourcesIncome;
			}
			set
			{
				if ((this._OtherSourcesIncome != value))
				{
					this.OnOtherSourcesIncomeChanging(value);
					this.SendPropertyChanging();
					this._OtherSourcesIncome = value;
					this.SendPropertyChanged("OtherSourcesIncome");
					this.OnOtherSourcesIncomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnnualSales", DbType="NVarChar(50)")]
		public string AnnualSales
		{
			get
			{
				return this._AnnualSales;
			}
			set
			{
				if ((this._AnnualSales != value))
				{
					this.OnAnnualSalesChanging(value);
					this.SendPropertyChanging();
					this._AnnualSales = value;
					this.SendPropertyChanged("AnnualSales");
					this.OnAnnualSalesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Political", DbType="Bit")]
		public System.Nullable<bool> Political
		{
			get
			{
				return this._Political;
			}
			set
			{
				if ((this._Political != value))
				{
					this.OnPoliticalChanging(value);
					this.SendPropertyChanging();
					this._Political = value;
					this.SendPropertyChanged("Political");
					this.OnPoliticalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PoliticalPosition", DbType="NVarChar(50)")]
		public string PoliticalPosition
		{
			get
			{
				return this._PoliticalPosition;
			}
			set
			{
				if ((this._PoliticalPosition != value))
				{
					this.OnPoliticalPositionChanging(value);
					this.SendPropertyChanging();
					this._PoliticalPosition = value;
					this.SendPropertyChanged("PoliticalPosition");
					this.OnPoliticalPositionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AddrWork")]
	public partial class AddrWork : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CustNo;
		
		private string _WorkplaceName;
		
		private string _No;
		
		private string _Street;
		
		private string _building;
		
		private string _alley;
		
		private string _locality;
		
		private string _District;
		
		private string _province;
		
		private string _ZipCode;
		
		private string _Tel;
		
		private string _Fax;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustNoChanging(string value);
    partial void OnCustNoChanged();
    partial void OnWorkplaceNameChanging(string value);
    partial void OnWorkplaceNameChanged();
    partial void OnNoChanging(string value);
    partial void OnNoChanged();
    partial void OnStreetChanging(string value);
    partial void OnStreetChanged();
    partial void OnbuildingChanging(string value);
    partial void OnbuildingChanged();
    partial void OnalleyChanging(string value);
    partial void OnalleyChanged();
    partial void OnlocalityChanging(string value);
    partial void OnlocalityChanged();
    partial void OnDistrictChanging(string value);
    partial void OnDistrictChanged();
    partial void OnprovinceChanging(string value);
    partial void OnprovinceChanged();
    partial void OnZipCodeChanging(string value);
    partial void OnZipCodeChanged();
    partial void OnTelChanging(string value);
    partial void OnTelChanged();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    #endregion
		
		public AddrWork()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CustNo
		{
			get
			{
				return this._CustNo;
			}
			set
			{
				if ((this._CustNo != value))
				{
					this.OnCustNoChanging(value);
					this.SendPropertyChanging();
					this._CustNo = value;
					this.SendPropertyChanged("CustNo");
					this.OnCustNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkplaceName", DbType="NVarChar(200)")]
		public string WorkplaceName
		{
			get
			{
				return this._WorkplaceName;
			}
			set
			{
				if ((this._WorkplaceName != value))
				{
					this.OnWorkplaceNameChanging(value);
					this.SendPropertyChanging();
					this._WorkplaceName = value;
					this.SendPropertyChanged("WorkplaceName");
					this.OnWorkplaceNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No", DbType="NVarChar(50)")]
		public string No
		{
			get
			{
				return this._No;
			}
			set
			{
				if ((this._No != value))
				{
					this.OnNoChanging(value);
					this.SendPropertyChanging();
					this._No = value;
					this.SendPropertyChanged("No");
					this.OnNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Street", DbType="NVarChar(50)")]
		public string Street
		{
			get
			{
				return this._Street;
			}
			set
			{
				if ((this._Street != value))
				{
					this.OnStreetChanging(value);
					this.SendPropertyChanging();
					this._Street = value;
					this.SendPropertyChanged("Street");
					this.OnStreetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_building", DbType="NVarChar(50)")]
		public string building
		{
			get
			{
				return this._building;
			}
			set
			{
				if ((this._building != value))
				{
					this.OnbuildingChanging(value);
					this.SendPropertyChanging();
					this._building = value;
					this.SendPropertyChanged("building");
					this.OnbuildingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alley", DbType="NVarChar(50)")]
		public string alley
		{
			get
			{
				return this._alley;
			}
			set
			{
				if ((this._alley != value))
				{
					this.OnalleyChanging(value);
					this.SendPropertyChanging();
					this._alley = value;
					this.SendPropertyChanged("alley");
					this.OnalleyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_locality", DbType="NVarChar(50)")]
		public string locality
		{
			get
			{
				return this._locality;
			}
			set
			{
				if ((this._locality != value))
				{
					this.OnlocalityChanging(value);
					this.SendPropertyChanging();
					this._locality = value;
					this.SendPropertyChanged("locality");
					this.OnlocalityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_District", DbType="NVarChar(50)")]
		public string District
		{
			get
			{
				return this._District;
			}
			set
			{
				if ((this._District != value))
				{
					this.OnDistrictChanging(value);
					this.SendPropertyChanging();
					this._District = value;
					this.SendPropertyChanged("District");
					this.OnDistrictChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_province", DbType="NVarChar(50)")]
		public string province
		{
			get
			{
				return this._province;
			}
			set
			{
				if ((this._province != value))
				{
					this.OnprovinceChanging(value);
					this.SendPropertyChanging();
					this._province = value;
					this.SendPropertyChanged("province");
					this.OnprovinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZipCode", DbType="NVarChar(50)")]
		public string ZipCode
		{
			get
			{
				return this._ZipCode;
			}
			set
			{
				if ((this._ZipCode != value))
				{
					this.OnZipCodeChanging(value);
					this.SendPropertyChanging();
					this._ZipCode = value;
					this.SendPropertyChanged("ZipCode");
					this.OnZipCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="NVarChar(50)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this.OnTelChanging(value);
					this.SendPropertyChanging();
					this._Tel = value;
					this.SendPropertyChanged("Tel");
					this.OnTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="NVarChar(50)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this.OnFaxChanging(value);
					this.SendPropertyChanging();
					this._Fax = value;
					this.SendPropertyChanged("Fax");
					this.OnFaxChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RefPerSonInformation")]
	public partial class RefPerSonInformation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CustNo;
		
		private string _Prefix1;
		
		private string _FName1;
		
		private string _LName1;
		
		private string _relationship;
		
		private string _career;
		
		private int _TypeIDAdrr;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustNoChanging(string value);
    partial void OnCustNoChanged();
    partial void OnPrefix1Changing(string value);
    partial void OnPrefix1Changed();
    partial void OnFName1Changing(string value);
    partial void OnFName1Changed();
    partial void OnLName1Changing(string value);
    partial void OnLName1Changed();
    partial void OnrelationshipChanging(string value);
    partial void OnrelationshipChanged();
    partial void OncareerChanging(string value);
    partial void OncareerChanged();
    partial void OnTypeIDAdrrChanging(int value);
    partial void OnTypeIDAdrrChanged();
    #endregion
		
		public RefPerSonInformation()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CustNo
		{
			get
			{
				return this._CustNo;
			}
			set
			{
				if ((this._CustNo != value))
				{
					this.OnCustNoChanging(value);
					this.SendPropertyChanging();
					this._CustNo = value;
					this.SendPropertyChanged("CustNo");
					this.OnCustNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prefix1", DbType="NVarChar(50)")]
		public string Prefix1
		{
			get
			{
				return this._Prefix1;
			}
			set
			{
				if ((this._Prefix1 != value))
				{
					this.OnPrefix1Changing(value);
					this.SendPropertyChanging();
					this._Prefix1 = value;
					this.SendPropertyChanged("Prefix1");
					this.OnPrefix1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FName1", DbType="NVarChar(50)")]
		public string FName1
		{
			get
			{
				return this._FName1;
			}
			set
			{
				if ((this._FName1 != value))
				{
					this.OnFName1Changing(value);
					this.SendPropertyChanging();
					this._FName1 = value;
					this.SendPropertyChanged("FName1");
					this.OnFName1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LName1", DbType="NVarChar(50)")]
		public string LName1
		{
			get
			{
				return this._LName1;
			}
			set
			{
				if ((this._LName1 != value))
				{
					this.OnLName1Changing(value);
					this.SendPropertyChanging();
					this._LName1 = value;
					this.SendPropertyChanged("LName1");
					this.OnLName1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_relationship", DbType="NVarChar(50)")]
		public string relationship
		{
			get
			{
				return this._relationship;
			}
			set
			{
				if ((this._relationship != value))
				{
					this.OnrelationshipChanging(value);
					this.SendPropertyChanging();
					this._relationship = value;
					this.SendPropertyChanged("relationship");
					this.OnrelationshipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_career", DbType="NVarChar(50)")]
		public string career
		{
			get
			{
				return this._career;
			}
			set
			{
				if ((this._career != value))
				{
					this.OncareerChanging(value);
					this.SendPropertyChanging();
					this._career = value;
					this.SendPropertyChanged("career");
					this.OncareerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeIDAdrr", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TypeIDAdrr
		{
			get
			{
				return this._TypeIDAdrr;
			}
			set
			{
				if ((this._TypeIDAdrr != value))
				{
					this.OnTypeIDAdrrChanging(value);
					this.SendPropertyChanging();
					this._TypeIDAdrr = value;
					this.SendPropertyChanged("TypeIDAdrr");
					this.OnTypeIDAdrrChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.InforCorporate")]
	public partial class InforCorporate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CustNo;
		
		private string _typecompany;
		
		private string _Name;
		
		private string _Nationality;
		
		private string _RegisterDate;
		
		private string _RegisterNo;
		
		private string _RegisteCountry;
		
		private string _TaxID;
		
		private string _typebisiness;
		
		private string _RegisteredCapital;
		
		private string _Paid_up_capital;
		
		private string _Another1;
		
		private string _Another2;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustNoChanging(string value);
    partial void OnCustNoChanged();
    partial void OntypecompanyChanging(string value);
    partial void OntypecompanyChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnNationalityChanging(string value);
    partial void OnNationalityChanged();
    partial void OnRegisterDateChanging(string value);
    partial void OnRegisterDateChanged();
    partial void OnRegisterNoChanging(string value);
    partial void OnRegisterNoChanged();
    partial void OnRegisteCountryChanging(string value);
    partial void OnRegisteCountryChanged();
    partial void OnTaxIDChanging(string value);
    partial void OnTaxIDChanged();
    partial void OntypebisinessChanging(string value);
    partial void OntypebisinessChanged();
    partial void OnRegisteredCapitalChanging(string value);
    partial void OnRegisteredCapitalChanged();
    partial void OnPaid_up_capitalChanging(string value);
    partial void OnPaid_up_capitalChanged();
    partial void OnAnother1Changing(string value);
    partial void OnAnother1Changed();
    partial void OnAnother2Changing(string value);
    partial void OnAnother2Changed();
    #endregion
		
		public InforCorporate()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CustNo
		{
			get
			{
				return this._CustNo;
			}
			set
			{
				if ((this._CustNo != value))
				{
					this.OnCustNoChanging(value);
					this.SendPropertyChanging();
					this._CustNo = value;
					this.SendPropertyChanged("CustNo");
					this.OnCustNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typecompany", DbType="NVarChar(50)")]
		public string typecompany
		{
			get
			{
				return this._typecompany;
			}
			set
			{
				if ((this._typecompany != value))
				{
					this.OntypecompanyChanging(value);
					this.SendPropertyChanging();
					this._typecompany = value;
					this.SendPropertyChanged("typecompany");
					this.OntypecompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nationality", DbType="NVarChar(50)")]
		public string Nationality
		{
			get
			{
				return this._Nationality;
			}
			set
			{
				if ((this._Nationality != value))
				{
					this.OnNationalityChanging(value);
					this.SendPropertyChanging();
					this._Nationality = value;
					this.SendPropertyChanged("Nationality");
					this.OnNationalityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegisterDate", DbType="NVarChar(50)")]
		public string RegisterDate
		{
			get
			{
				return this._RegisterDate;
			}
			set
			{
				if ((this._RegisterDate != value))
				{
					this.OnRegisterDateChanging(value);
					this.SendPropertyChanging();
					this._RegisterDate = value;
					this.SendPropertyChanged("RegisterDate");
					this.OnRegisterDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegisterNo", DbType="NVarChar(50)")]
		public string RegisterNo
		{
			get
			{
				return this._RegisterNo;
			}
			set
			{
				if ((this._RegisterNo != value))
				{
					this.OnRegisterNoChanging(value);
					this.SendPropertyChanging();
					this._RegisterNo = value;
					this.SendPropertyChanged("RegisterNo");
					this.OnRegisterNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegisteCountry", DbType="NVarChar(50)")]
		public string RegisteCountry
		{
			get
			{
				return this._RegisteCountry;
			}
			set
			{
				if ((this._RegisteCountry != value))
				{
					this.OnRegisteCountryChanging(value);
					this.SendPropertyChanging();
					this._RegisteCountry = value;
					this.SendPropertyChanged("RegisteCountry");
					this.OnRegisteCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxID", DbType="NVarChar(50)")]
		public string TaxID
		{
			get
			{
				return this._TaxID;
			}
			set
			{
				if ((this._TaxID != value))
				{
					this.OnTaxIDChanging(value);
					this.SendPropertyChanging();
					this._TaxID = value;
					this.SendPropertyChanged("TaxID");
					this.OnTaxIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typebisiness", DbType="NVarChar(50)")]
		public string typebisiness
		{
			get
			{
				return this._typebisiness;
			}
			set
			{
				if ((this._typebisiness != value))
				{
					this.OntypebisinessChanging(value);
					this.SendPropertyChanging();
					this._typebisiness = value;
					this.SendPropertyChanged("typebisiness");
					this.OntypebisinessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegisteredCapital", DbType="NVarChar(50)")]
		public string RegisteredCapital
		{
			get
			{
				return this._RegisteredCapital;
			}
			set
			{
				if ((this._RegisteredCapital != value))
				{
					this.OnRegisteredCapitalChanging(value);
					this.SendPropertyChanging();
					this._RegisteredCapital = value;
					this.SendPropertyChanged("RegisteredCapital");
					this.OnRegisteredCapitalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paid_up_capital", DbType="NVarChar(50)")]
		public string Paid_up_capital
		{
			get
			{
				return this._Paid_up_capital;
			}
			set
			{
				if ((this._Paid_up_capital != value))
				{
					this.OnPaid_up_capitalChanging(value);
					this.SendPropertyChanging();
					this._Paid_up_capital = value;
					this.SendPropertyChanged("Paid_up_capital");
					this.OnPaid_up_capitalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Another1", DbType="NVarChar(500)")]
		public string Another1
		{
			get
			{
				return this._Another1;
			}
			set
			{
				if ((this._Another1 != value))
				{
					this.OnAnother1Changing(value);
					this.SendPropertyChanging();
					this._Another1 = value;
					this.SendPropertyChanged("Another1");
					this.OnAnother1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Another2", DbType="NVarChar(500)")]
		public string Another2
		{
			get
			{
				return this._Another2;
			}
			set
			{
				if ((this._Another2 != value))
				{
					this.OnAnother2Changing(value);
					this.SendPropertyChanging();
					this._Another2 = value;
					this.SendPropertyChanged("Another2");
					this.OnAnother2Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TypeCareer")]
	public partial class TypeCareer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Code;
		
		private string _Description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public TypeCareer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(50)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(50)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AddrCurrent")]
	public partial class AddrCurrent : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CustNo;
		
		private string _NameLocal;
		
		private string _No;
		
		private int _TypeIDAdrr;
		
		private string _Street;
		
		private string _Building;
		
		private string _Alley;
		
		private string _Locality;
		
		private string _District;
		
		private string _Province;
		
		private string _ZipCode;
		
		private string _Tel;
		
		private string _TelPhone;
		
		private string _fax;
		
		private string _Email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustNoChanging(string value);
    partial void OnCustNoChanged();
    partial void OnNameLocalChanging(string value);
    partial void OnNameLocalChanged();
    partial void OnNoChanging(string value);
    partial void OnNoChanged();
    partial void OnTypeIDAdrrChanging(int value);
    partial void OnTypeIDAdrrChanged();
    partial void OnStreetChanging(string value);
    partial void OnStreetChanged();
    partial void OnBuildingChanging(string value);
    partial void OnBuildingChanged();
    partial void OnAlleyChanging(string value);
    partial void OnAlleyChanged();
    partial void OnLocalityChanging(string value);
    partial void OnLocalityChanged();
    partial void OnDistrictChanging(string value);
    partial void OnDistrictChanged();
    partial void OnProvinceChanging(string value);
    partial void OnProvinceChanged();
    partial void OnZipCodeChanging(string value);
    partial void OnZipCodeChanged();
    partial void OnTelChanging(string value);
    partial void OnTelChanged();
    partial void OnTelPhoneChanging(string value);
    partial void OnTelPhoneChanged();
    partial void OnfaxChanging(string value);
    partial void OnfaxChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public AddrCurrent()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CustNo
		{
			get
			{
				return this._CustNo;
			}
			set
			{
				if ((this._CustNo != value))
				{
					this.OnCustNoChanging(value);
					this.SendPropertyChanging();
					this._CustNo = value;
					this.SendPropertyChanged("CustNo");
					this.OnCustNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameLocal", DbType="NVarChar(50)")]
		public string NameLocal
		{
			get
			{
				return this._NameLocal;
			}
			set
			{
				if ((this._NameLocal != value))
				{
					this.OnNameLocalChanging(value);
					this.SendPropertyChanging();
					this._NameLocal = value;
					this.SendPropertyChanged("NameLocal");
					this.OnNameLocalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No", DbType="NVarChar(50)")]
		public string No
		{
			get
			{
				return this._No;
			}
			set
			{
				if ((this._No != value))
				{
					this.OnNoChanging(value);
					this.SendPropertyChanging();
					this._No = value;
					this.SendPropertyChanged("No");
					this.OnNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeIDAdrr", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TypeIDAdrr
		{
			get
			{
				return this._TypeIDAdrr;
			}
			set
			{
				if ((this._TypeIDAdrr != value))
				{
					this.OnTypeIDAdrrChanging(value);
					this.SendPropertyChanging();
					this._TypeIDAdrr = value;
					this.SendPropertyChanged("TypeIDAdrr");
					this.OnTypeIDAdrrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Street", DbType="NVarChar(50)")]
		public string Street
		{
			get
			{
				return this._Street;
			}
			set
			{
				if ((this._Street != value))
				{
					this.OnStreetChanging(value);
					this.SendPropertyChanging();
					this._Street = value;
					this.SendPropertyChanged("Street");
					this.OnStreetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Building", DbType="NVarChar(50)")]
		public string Building
		{
			get
			{
				return this._Building;
			}
			set
			{
				if ((this._Building != value))
				{
					this.OnBuildingChanging(value);
					this.SendPropertyChanging();
					this._Building = value;
					this.SendPropertyChanged("Building");
					this.OnBuildingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alley", DbType="NVarChar(50)")]
		public string Alley
		{
			get
			{
				return this._Alley;
			}
			set
			{
				if ((this._Alley != value))
				{
					this.OnAlleyChanging(value);
					this.SendPropertyChanging();
					this._Alley = value;
					this.SendPropertyChanged("Alley");
					this.OnAlleyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Locality", DbType="NVarChar(50)")]
		public string Locality
		{
			get
			{
				return this._Locality;
			}
			set
			{
				if ((this._Locality != value))
				{
					this.OnLocalityChanging(value);
					this.SendPropertyChanging();
					this._Locality = value;
					this.SendPropertyChanged("Locality");
					this.OnLocalityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_District", DbType="NVarChar(50)")]
		public string District
		{
			get
			{
				return this._District;
			}
			set
			{
				if ((this._District != value))
				{
					this.OnDistrictChanging(value);
					this.SendPropertyChanging();
					this._District = value;
					this.SendPropertyChanged("District");
					this.OnDistrictChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Province", DbType="NVarChar(50)")]
		public string Province
		{
			get
			{
				return this._Province;
			}
			set
			{
				if ((this._Province != value))
				{
					this.OnProvinceChanging(value);
					this.SendPropertyChanging();
					this._Province = value;
					this.SendPropertyChanged("Province");
					this.OnProvinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZipCode", DbType="NVarChar(50)")]
		public string ZipCode
		{
			get
			{
				return this._ZipCode;
			}
			set
			{
				if ((this._ZipCode != value))
				{
					this.OnZipCodeChanging(value);
					this.SendPropertyChanging();
					this._ZipCode = value;
					this.SendPropertyChanged("ZipCode");
					this.OnZipCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="NVarChar(50)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this.OnTelChanging(value);
					this.SendPropertyChanging();
					this._Tel = value;
					this.SendPropertyChanged("Tel");
					this.OnTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelPhone", DbType="NVarChar(50)")]
		public string TelPhone
		{
			get
			{
				return this._TelPhone;
			}
			set
			{
				if ((this._TelPhone != value))
				{
					this.OnTelPhoneChanging(value);
					this.SendPropertyChanging();
					this._TelPhone = value;
					this.SendPropertyChanged("TelPhone");
					this.OnTelPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax", DbType="NVarChar(50)")]
		public string fax
		{
			get
			{
				return this._fax;
			}
			set
			{
				if ((this._fax != value))
				{
					this.OnfaxChanging(value);
					this.SendPropertyChanging();
					this._fax = value;
					this.SendPropertyChanged("fax");
					this.OnfaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.InforPayment")]
	public partial class InforPayment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CustNo;
		
		private System.Nullable<bool> _ATS;
		
		private string _Bank_1;
		
		private string _Branch1;
		
		private string _AccountN01;
		
		private string _TypeAccount1;
		
		private System.Nullable<bool> _e_Dividend;
		
		private string _Bank2;
		
		private string _Branch2;
		
		private string _AccountN02;
		
		private string _TypeAccount2;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustNoChanging(string value);
    partial void OnCustNoChanged();
    partial void OnATSChanging(System.Nullable<bool> value);
    partial void OnATSChanged();
    partial void OnBank_1Changing(string value);
    partial void OnBank_1Changed();
    partial void OnBranch1Changing(string value);
    partial void OnBranch1Changed();
    partial void OnAccountN01Changing(string value);
    partial void OnAccountN01Changed();
    partial void OnTypeAccount1Changing(string value);
    partial void OnTypeAccount1Changed();
    partial void One_DividendChanging(System.Nullable<bool> value);
    partial void One_DividendChanged();
    partial void OnBank2Changing(string value);
    partial void OnBank2Changed();
    partial void OnBranch2Changing(string value);
    partial void OnBranch2Changed();
    partial void OnAccountN02Changing(string value);
    partial void OnAccountN02Changed();
    partial void OnTypeAccount2Changing(string value);
    partial void OnTypeAccount2Changed();
    #endregion
		
		public InforPayment()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CustNo
		{
			get
			{
				return this._CustNo;
			}
			set
			{
				if ((this._CustNo != value))
				{
					this.OnCustNoChanging(value);
					this.SendPropertyChanging();
					this._CustNo = value;
					this.SendPropertyChanged("CustNo");
					this.OnCustNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATS", DbType="Bit")]
		public System.Nullable<bool> ATS
		{
			get
			{
				return this._ATS;
			}
			set
			{
				if ((this._ATS != value))
				{
					this.OnATSChanging(value);
					this.SendPropertyChanging();
					this._ATS = value;
					this.SendPropertyChanged("ATS");
					this.OnATSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bank_1", DbType="NVarChar(50)")]
		public string Bank_1
		{
			get
			{
				return this._Bank_1;
			}
			set
			{
				if ((this._Bank_1 != value))
				{
					this.OnBank_1Changing(value);
					this.SendPropertyChanging();
					this._Bank_1 = value;
					this.SendPropertyChanged("Bank_1");
					this.OnBank_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Branch1", DbType="NVarChar(50)")]
		public string Branch1
		{
			get
			{
				return this._Branch1;
			}
			set
			{
				if ((this._Branch1 != value))
				{
					this.OnBranch1Changing(value);
					this.SendPropertyChanging();
					this._Branch1 = value;
					this.SendPropertyChanged("Branch1");
					this.OnBranch1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountN01", DbType="NVarChar(50)")]
		public string AccountN01
		{
			get
			{
				return this._AccountN01;
			}
			set
			{
				if ((this._AccountN01 != value))
				{
					this.OnAccountN01Changing(value);
					this.SendPropertyChanging();
					this._AccountN01 = value;
					this.SendPropertyChanged("AccountN01");
					this.OnAccountN01Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeAccount1", DbType="NVarChar(50)")]
		public string TypeAccount1
		{
			get
			{
				return this._TypeAccount1;
			}
			set
			{
				if ((this._TypeAccount1 != value))
				{
					this.OnTypeAccount1Changing(value);
					this.SendPropertyChanging();
					this._TypeAccount1 = value;
					this.SendPropertyChanged("TypeAccount1");
					this.OnTypeAccount1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_Dividend", DbType="Bit")]
		public System.Nullable<bool> e_Dividend
		{
			get
			{
				return this._e_Dividend;
			}
			set
			{
				if ((this._e_Dividend != value))
				{
					this.One_DividendChanging(value);
					this.SendPropertyChanging();
					this._e_Dividend = value;
					this.SendPropertyChanged("e_Dividend");
					this.One_DividendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bank2", DbType="NVarChar(50)")]
		public string Bank2
		{
			get
			{
				return this._Bank2;
			}
			set
			{
				if ((this._Bank2 != value))
				{
					this.OnBank2Changing(value);
					this.SendPropertyChanging();
					this._Bank2 = value;
					this.SendPropertyChanged("Bank2");
					this.OnBank2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Branch2", DbType="NVarChar(50)")]
		public string Branch2
		{
			get
			{
				return this._Branch2;
			}
			set
			{
				if ((this._Branch2 != value))
				{
					this.OnBranch2Changing(value);
					this.SendPropertyChanging();
					this._Branch2 = value;
					this.SendPropertyChanged("Branch2");
					this.OnBranch2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountN02", DbType="NVarChar(50)")]
		public string AccountN02
		{
			get
			{
				return this._AccountN02;
			}
			set
			{
				if ((this._AccountN02 != value))
				{
					this.OnAccountN02Changing(value);
					this.SendPropertyChanging();
					this._AccountN02 = value;
					this.SendPropertyChanged("AccountN02");
					this.OnAccountN02Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeAccount2", DbType="NVarChar(50)")]
		public string TypeAccount2
		{
			get
			{
				return this._TypeAccount2;
			}
			set
			{
				if ((this._TypeAccount2 != value))
				{
					this.OnTypeAccount2Changing(value);
					this.SendPropertyChanging();
					this._TypeAccount2 = value;
					this.SendPropertyChanged("TypeAccount2");
					this.OnTypeAccount2Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GenerateLink")]
	public partial class GenerateLink : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CustNo;
		
		private string _Link;
		
		private string _htmlGen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustNoChanging(string value);
    partial void OnCustNoChanged();
    partial void OnLinkChanging(string value);
    partial void OnLinkChanged();
    partial void OnhtmlGenChanging(string value);
    partial void OnhtmlGenChanged();
    #endregion
		
		public GenerateLink()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CustNo
		{
			get
			{
				return this._CustNo;
			}
			set
			{
				if ((this._CustNo != value))
				{
					this.OnCustNoChanging(value);
					this.SendPropertyChanging();
					this._CustNo = value;
					this.SendPropertyChanged("CustNo");
					this.OnCustNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link", DbType="NVarChar(2000)")]
		public string Link
		{
			get
			{
				return this._Link;
			}
			set
			{
				if ((this._Link != value))
				{
					this.OnLinkChanging(value);
					this.SendPropertyChanging();
					this._Link = value;
					this.SendPropertyChanged("Link");
					this.OnLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_htmlGen", DbType="NVarChar(200)")]
		public string htmlGen
		{
			get
			{
				return this._htmlGen;
			}
			set
			{
				if ((this._htmlGen != value))
				{
					this.OnhtmlGenChanging(value);
					this.SendPropertyChanging();
					this._htmlGen = value;
					this.SendPropertyChanged("htmlGen");
					this.OnhtmlGenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Account")]
	public partial class Account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CustNo;
		
		private string _draft_date;
		
		private string _type_Account;
		
		private System.Nullable<decimal> _total_limit;
		
		private System.Nullable<bool> _a_1;
		
		private System.Nullable<bool> _a_2;
		
		private System.Nullable<bool> _a_3;
		
		private string _CustNo_Mate;
		
		private string _SendAddr;
		
		private string _suggester_name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustNoChanging(string value);
    partial void OnCustNoChanged();
    partial void Ondraft_dateChanging(string value);
    partial void Ondraft_dateChanged();
    partial void Ontype_AccountChanging(string value);
    partial void Ontype_AccountChanged();
    partial void Ontotal_limitChanging(System.Nullable<decimal> value);
    partial void Ontotal_limitChanged();
    partial void Ona_1Changing(System.Nullable<bool> value);
    partial void Ona_1Changed();
    partial void Ona_2Changing(System.Nullable<bool> value);
    partial void Ona_2Changed();
    partial void Ona_3Changing(System.Nullable<bool> value);
    partial void Ona_3Changed();
    partial void OnCustNo_MateChanging(string value);
    partial void OnCustNo_MateChanged();
    partial void OnSendAddrChanging(string value);
    partial void OnSendAddrChanged();
    partial void Onsuggester_nameChanging(string value);
    partial void Onsuggester_nameChanged();
    #endregion
		
		public Account()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CustNo
		{
			get
			{
				return this._CustNo;
			}
			set
			{
				if ((this._CustNo != value))
				{
					this.OnCustNoChanging(value);
					this.SendPropertyChanging();
					this._CustNo = value;
					this.SendPropertyChanged("CustNo");
					this.OnCustNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_draft_date", DbType="NVarChar(50)")]
		public string draft_date
		{
			get
			{
				return this._draft_date;
			}
			set
			{
				if ((this._draft_date != value))
				{
					this.Ondraft_dateChanging(value);
					this.SendPropertyChanging();
					this._draft_date = value;
					this.SendPropertyChanged("draft_date");
					this.Ondraft_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type_Account", DbType="NVarChar(50)")]
		public string type_Account
		{
			get
			{
				return this._type_Account;
			}
			set
			{
				if ((this._type_Account != value))
				{
					this.Ontype_AccountChanging(value);
					this.SendPropertyChanging();
					this._type_Account = value;
					this.SendPropertyChanged("type_Account");
					this.Ontype_AccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_limit", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> total_limit
		{
			get
			{
				return this._total_limit;
			}
			set
			{
				if ((this._total_limit != value))
				{
					this.Ontotal_limitChanging(value);
					this.SendPropertyChanging();
					this._total_limit = value;
					this.SendPropertyChanged("total_limit");
					this.Ontotal_limitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_1", DbType="Bit")]
		public System.Nullable<bool> a_1
		{
			get
			{
				return this._a_1;
			}
			set
			{
				if ((this._a_1 != value))
				{
					this.Ona_1Changing(value);
					this.SendPropertyChanging();
					this._a_1 = value;
					this.SendPropertyChanged("a_1");
					this.Ona_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_2", DbType="Bit")]
		public System.Nullable<bool> a_2
		{
			get
			{
				return this._a_2;
			}
			set
			{
				if ((this._a_2 != value))
				{
					this.Ona_2Changing(value);
					this.SendPropertyChanging();
					this._a_2 = value;
					this.SendPropertyChanged("a_2");
					this.Ona_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_3", DbType="Bit")]
		public System.Nullable<bool> a_3
		{
			get
			{
				return this._a_3;
			}
			set
			{
				if ((this._a_3 != value))
				{
					this.Ona_3Changing(value);
					this.SendPropertyChanging();
					this._a_3 = value;
					this.SendPropertyChanged("a_3");
					this.Ona_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustNo_Mate", DbType="NVarChar(50)")]
		public string CustNo_Mate
		{
			get
			{
				return this._CustNo_Mate;
			}
			set
			{
				if ((this._CustNo_Mate != value))
				{
					this.OnCustNo_MateChanging(value);
					this.SendPropertyChanging();
					this._CustNo_Mate = value;
					this.SendPropertyChanged("CustNo_Mate");
					this.OnCustNo_MateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendAddr", DbType="NVarChar(50)")]
		public string SendAddr
		{
			get
			{
				return this._SendAddr;
			}
			set
			{
				if ((this._SendAddr != value))
				{
					this.OnSendAddrChanging(value);
					this.SendPropertyChanging();
					this._SendAddr = value;
					this.SendPropertyChanged("SendAddr");
					this.OnSendAddrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_suggester_name", DbType="NVarChar(50)")]
		public string suggester_name
		{
			get
			{
				return this._suggester_name;
			}
			set
			{
				if ((this._suggester_name != value))
				{
					this.Onsuggester_nameChanging(value);
					this.SendPropertyChanging();
					this._suggester_name = value;
					this.SendPropertyChanged("suggester_name");
					this.Onsuggester_nameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CustInformation")]
	public partial class CustInformation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CustNo;
		
		private string _Prefix1;
		
		private string _FName1;
		
		private string _LName1;
		
		private string _Prefix2;
		
		private string _FName2;
		
		private string _LName2;
		
		private string _BirthDate;
		
		private string _IDCard;
		
		private string _IDGovernment;
		
		private string _Nationality;
		
		private string _PassportNo;
		
		private string _Expired;
		
		private string _CreateDate;
		
		private string _Tel;
		
		private string _MaritalStatus;
		
		private System.Nullable<bool> _Guilty;
		
		private string _GuiltyDes;
		
		private string _GuiltyYear;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustNoChanging(string value);
    partial void OnCustNoChanged();
    partial void OnPrefix1Changing(string value);
    partial void OnPrefix1Changed();
    partial void OnFName1Changing(string value);
    partial void OnFName1Changed();
    partial void OnLName1Changing(string value);
    partial void OnLName1Changed();
    partial void OnPrefix2Changing(string value);
    partial void OnPrefix2Changed();
    partial void OnFName2Changing(string value);
    partial void OnFName2Changed();
    partial void OnLName2Changing(string value);
    partial void OnLName2Changed();
    partial void OnBirthDateChanging(string value);
    partial void OnBirthDateChanged();
    partial void OnIDCardChanging(string value);
    partial void OnIDCardChanged();
    partial void OnIDGovernmentChanging(string value);
    partial void OnIDGovernmentChanged();
    partial void OnNationalityChanging(string value);
    partial void OnNationalityChanged();
    partial void OnPassportNoChanging(string value);
    partial void OnPassportNoChanged();
    partial void OnExpiredChanging(string value);
    partial void OnExpiredChanged();
    partial void OnCreateDateChanging(string value);
    partial void OnCreateDateChanged();
    partial void OnTelChanging(string value);
    partial void OnTelChanged();
    partial void OnMaritalStatusChanging(string value);
    partial void OnMaritalStatusChanged();
    partial void OnGuiltyChanging(System.Nullable<bool> value);
    partial void OnGuiltyChanged();
    partial void OnGuiltyDesChanging(string value);
    partial void OnGuiltyDesChanged();
    partial void OnGuiltyYearChanging(string value);
    partial void OnGuiltyYearChanged();
    #endregion
		
		public CustInformation()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CustNo
		{
			get
			{
				return this._CustNo;
			}
			set
			{
				if ((this._CustNo != value))
				{
					this.OnCustNoChanging(value);
					this.SendPropertyChanging();
					this._CustNo = value;
					this.SendPropertyChanged("CustNo");
					this.OnCustNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prefix1", DbType="NVarChar(50)")]
		public string Prefix1
		{
			get
			{
				return this._Prefix1;
			}
			set
			{
				if ((this._Prefix1 != value))
				{
					this.OnPrefix1Changing(value);
					this.SendPropertyChanging();
					this._Prefix1 = value;
					this.SendPropertyChanged("Prefix1");
					this.OnPrefix1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FName1", DbType="NVarChar(50)")]
		public string FName1
		{
			get
			{
				return this._FName1;
			}
			set
			{
				if ((this._FName1 != value))
				{
					this.OnFName1Changing(value);
					this.SendPropertyChanging();
					this._FName1 = value;
					this.SendPropertyChanged("FName1");
					this.OnFName1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LName1", DbType="NVarChar(50)")]
		public string LName1
		{
			get
			{
				return this._LName1;
			}
			set
			{
				if ((this._LName1 != value))
				{
					this.OnLName1Changing(value);
					this.SendPropertyChanging();
					this._LName1 = value;
					this.SendPropertyChanged("LName1");
					this.OnLName1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prefix2", DbType="NVarChar(50)")]
		public string Prefix2
		{
			get
			{
				return this._Prefix2;
			}
			set
			{
				if ((this._Prefix2 != value))
				{
					this.OnPrefix2Changing(value);
					this.SendPropertyChanging();
					this._Prefix2 = value;
					this.SendPropertyChanged("Prefix2");
					this.OnPrefix2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FName2", DbType="NVarChar(50)")]
		public string FName2
		{
			get
			{
				return this._FName2;
			}
			set
			{
				if ((this._FName2 != value))
				{
					this.OnFName2Changing(value);
					this.SendPropertyChanging();
					this._FName2 = value;
					this.SendPropertyChanged("FName2");
					this.OnFName2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LName2", DbType="NVarChar(50)")]
		public string LName2
		{
			get
			{
				return this._LName2;
			}
			set
			{
				if ((this._LName2 != value))
				{
					this.OnLName2Changing(value);
					this.SendPropertyChanging();
					this._LName2 = value;
					this.SendPropertyChanged("LName2");
					this.OnLName2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirthDate", DbType="NVarChar(50)")]
		public string BirthDate
		{
			get
			{
				return this._BirthDate;
			}
			set
			{
				if ((this._BirthDate != value))
				{
					this.OnBirthDateChanging(value);
					this.SendPropertyChanging();
					this._BirthDate = value;
					this.SendPropertyChanged("BirthDate");
					this.OnBirthDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCard", DbType="NVarChar(50)")]
		public string IDCard
		{
			get
			{
				return this._IDCard;
			}
			set
			{
				if ((this._IDCard != value))
				{
					this.OnIDCardChanging(value);
					this.SendPropertyChanging();
					this._IDCard = value;
					this.SendPropertyChanged("IDCard");
					this.OnIDCardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDGovernment", DbType="NVarChar(50)")]
		public string IDGovernment
		{
			get
			{
				return this._IDGovernment;
			}
			set
			{
				if ((this._IDGovernment != value))
				{
					this.OnIDGovernmentChanging(value);
					this.SendPropertyChanging();
					this._IDGovernment = value;
					this.SendPropertyChanged("IDGovernment");
					this.OnIDGovernmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nationality", DbType="NVarChar(50)")]
		public string Nationality
		{
			get
			{
				return this._Nationality;
			}
			set
			{
				if ((this._Nationality != value))
				{
					this.OnNationalityChanging(value);
					this.SendPropertyChanging();
					this._Nationality = value;
					this.SendPropertyChanged("Nationality");
					this.OnNationalityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassportNo", DbType="NVarChar(50)")]
		public string PassportNo
		{
			get
			{
				return this._PassportNo;
			}
			set
			{
				if ((this._PassportNo != value))
				{
					this.OnPassportNoChanging(value);
					this.SendPropertyChanging();
					this._PassportNo = value;
					this.SendPropertyChanged("PassportNo");
					this.OnPassportNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expired", DbType="NVarChar(50)")]
		public string Expired
		{
			get
			{
				return this._Expired;
			}
			set
			{
				if ((this._Expired != value))
				{
					this.OnExpiredChanging(value);
					this.SendPropertyChanging();
					this._Expired = value;
					this.SendPropertyChanged("Expired");
					this.OnExpiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="NVarChar(50)")]
		public string CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="NVarChar(50)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this.OnTelChanging(value);
					this.SendPropertyChanging();
					this._Tel = value;
					this.SendPropertyChanged("Tel");
					this.OnTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaritalStatus", DbType="NVarChar(50)")]
		public string MaritalStatus
		{
			get
			{
				return this._MaritalStatus;
			}
			set
			{
				if ((this._MaritalStatus != value))
				{
					this.OnMaritalStatusChanging(value);
					this.SendPropertyChanging();
					this._MaritalStatus = value;
					this.SendPropertyChanged("MaritalStatus");
					this.OnMaritalStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guilty", DbType="Bit")]
		public System.Nullable<bool> Guilty
		{
			get
			{
				return this._Guilty;
			}
			set
			{
				if ((this._Guilty != value))
				{
					this.OnGuiltyChanging(value);
					this.SendPropertyChanging();
					this._Guilty = value;
					this.SendPropertyChanged("Guilty");
					this.OnGuiltyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuiltyDes", DbType="NVarChar(50)")]
		public string GuiltyDes
		{
			get
			{
				return this._GuiltyDes;
			}
			set
			{
				if ((this._GuiltyDes != value))
				{
					this.OnGuiltyDesChanging(value);
					this.SendPropertyChanging();
					this._GuiltyDes = value;
					this.SendPropertyChanged("GuiltyDes");
					this.OnGuiltyDesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuiltyYear", DbType="NVarChar(50)")]
		public string GuiltyYear
		{
			get
			{
				return this._GuiltyYear;
			}
			set
			{
				if ((this._GuiltyYear != value))
				{
					this.OnGuiltyYearChanging(value);
					this.SendPropertyChanging();
					this._GuiltyYear = value;
					this.SendPropertyChanged("GuiltyYear");
					this.OnGuiltyYearChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
